### ISSUE TITLE
Error: spawn udevadm ENOENT

### ISSUE THREAD

**Issue by QHose** [ebaauw/homebridge-p1#18]
Hi,

Node: 10.15.2, latest homebridge on PI

Thanks for creating this module, I tried to install it, but I do get this error. I tested separately that I do receive the telegrams on my usb1 port, so I added that one in the config.

``` "accessories": [],
    "platforms": [
        {
            "platform": "P1",
            "serialport": "/dev/ttyUSB1"
        },
        {
            "platform": "Hue",
            "host": [
                "192.168.1.115:8080",
                "192.168.1.122"
            ],
            "users": {```


```[4/12/2019, 11:01:04 AM] [Hue] homebridge-hue v0.11.20, node v10.15.3, homebridge v0.4.48
[4/12/2019, 11:01:04 AM] Loading 0 accessories...
(node:4676) UnhandledPromiseRejectionWarning: Error: spawn udevadm ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:240:19)
    at onErrorNT (internal/child_process.js:415:16)
    at process._tickCallback (internal/process/next_tick.js:63:19)
(node:4676) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:4676) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
[4/12/2019, 11:01:04 AM] [Hue] GateWayRaspBee: dresden elektronik deCONZ gateway v2.5.23, api v1.0.9
[4/12/2019, 11:01:04 AM] [Hue] GateWayRaspBee: warning: not using recommended deCONZ gateway version 2.5.60```

**Comment by ebaauw** [comment]
Are you running homebridge in a container?  I'm afraid I cannot help you in that case, see https://github.com/ebaauw/homebridge-p1/issues/13.

If not: are you running homebridge under user `pi` or under another user?  Is `/sbin` in that user's $PATH?

**Comment by QHose** [comment]
Thank you, I thought I was running it directly, I still saw an apparently old homebridge process running, but it is inside a container, so I will try to run the direct one as well. 

![image](https://user-images.githubusercontent.com/12411165/56075706-ffeada80-5dc6-11e9-90c0-ffd6ba7077c6.png)
