### ISSUE TITLE
No Data available within Eve

### ISSUE THREAD

**Issue by Vaoske** [ebaauw/homebridge-p1#24]
Hi,

I use homebridge-p1 v0.2.28 and for several days no history available within the Eve app.
Any solution?

greets,
Vaoske

**Comment by ebaauw** [comment]
Do you see the normal data in Eve?  Does _Last Updated_ change?  Did homebridge-p1 create (non-empty) history files in `~/.homebridge/accessories`?  Is the history empty on one iOS device or on multiple?

**Comment by abko** [comment]
I am experiencing a similar problem. 

With me I do so normal data in Eve, Last updated does change. When I checked I had history files in the accessories folder (in my setup in /var/lib/homebridge/accessories):
```
-rw-r--r-- 1 homebridge homebridge  87399 Jun 29 15:14 history_E0052004401136718.json
-rw-r--r-- 1 homebridge homebridge  82268 Jun 29 15:14 history_G0032565577616718.json
```

But I don't see updates since Jun 29. I am not sure what changed around that time, likely nodejs or homebridge-p1.

I removed the history files and rebooted, but that makes no difference.

Not sure what could be wrong in my setup.

**Comment by ebaauw** [comment]
Indeed, history is now persisted in `cachedAccessories`.  The old history files are no longer used, and can be deleted.

Not sure why Eve won't show any history.  Is this on one or on multiple devices?  Can you double-check running `homebridge -D` that Homebridge P1 writes history entries?  There should be a debug message on startup, how many history entries were restored.

If the message is there, there's probably something wrong the the time sync between Eve and Homebridge P1.  Best delete the history from Eve (under _Measurements_), force-quit Eve, and wait 10 minutes (for Homebridge P1 to write a new history entry).

**Comment by abko** [comment]
Thanks a lot for the prompt response and help. I was only able to check it now. It was your last suggestion. After deleting data under measurements, and the other steps, I started to see history again.
Thanks! Also for the nice and great quality plugin.

**Comment by abko** [comment]
Today Stedin replaced my energy meter with the iskra am550. Does the plugin work with it's P1 port as well? I notice the following in the log:

`[9/21/2020, 16:50:32] [P1] warning: 1-0:99.97.0: ignoring unknown value ()
[9/21/2020, 16:50:32] [P1] Electricity: set Current Consumption from 223 W to 217 W
[9/21/2020, 16:50:32] [P1] Electricity: set Last Updated from "Mon Sep 21 2020 17:50:29" to "Mon Sep 21 2020 17:50:30"
[9/21/2020, 16:50:32] [P1] Electricity L1: set Current Consumption from 220 W to 219 W
[9/21/2020, 16:50:32] [P1] Electricity L1: set Voltage from 228.1 V to 227.9 V
[9/21/2020, 16:50:32] [P1] Electricity L2: set Voltage from 228.2 V to 228.1 V
[9/21/2020, 16:50:32] [P1] Electricity L3: set Voltage from 228.6 V to 228.8 V
`

I see the consumption, but not the history anymore (also after clearing data in Eve)

**Comment by ebaauw** [comment]
The new meter might have a different serial number and therefore be exposed as a different accessory by Homebridge P1.  Are you sure you're not looking at the old accessory (which would still be in `cachedAccessories`)?

> [9/21/2020, 16:50:32] [P1] warning: 1-0:99.97.0: ignoring unknown value ()

That's the code for the incident log.  Apparently Homebridge P1 cannot parse the value reported.  Could you please list the telegram as written to the debug log on startup?  This won't break anything, though, because Homebridge P1 ignores the log anyways.

**Comment by abko** [comment]
Thanks again! Indeed I overlooked a second Electricity accessory. The original one is there still as well as a Gas accessory. Also the Gas accessory does not seem to update.

This is the telegram from the log, it's also followed by an error.

`[9/21/2020, 16:49:41] [P1] telegram:
ISK5\2M550T-1013

1-3:0.2.8(50)
0-0:1.0.0(200921174939S)
0-0:96.1.1(4530303534303037363138393538303230)
1-0:1.8.1(000000.000*kWh)
1-0:1.8.2(000001.118*kWh)
1-0:2.8.1(000000.000*kWh)
1-0:2.8.2(000000.000*kWh)
0-0:96.14.0(0002)
1-0:1.7.0(00.234*kW)
1-0:2.7.0(00.000*kW)
0-0:96.7.21(00006)
0-0:96.7.9(00002)
1-0:99.97.0()
1-0:32.32.0(00000)
1-0:52.32.0(00000)
1-0:72.32.0(00000)
1-0:32.36.0(00001)
1-0:52.36.0(00001)
1-0:72.36.0(00001)
0-0:96.13.0()
1-0:32.7.0(228.2*V)
1-0:52.7.0(227.9*V)
1-0:72.7.0(228.1*V)
1-0:31.7.0(001*A)
1-0:51.7.0(000*A)
1-0:71.7.0(000*A)
1-0:21.7.0(00.227*kW)
1-0:41.7.0(00.000*kW)
1-0:61.7.0(00.000*kW)
1-0:22.7.0(00.000*kW)
1-0:42.7.0(00.000*kW)
1-0:62.7.0(00.000*kW)
0-1:24.1.0(003)
0-1:96.1.0()
0-1:24.2.1(200921174506S)(02236.009*m3)
!4E76

[9/21/2020, 16:49:41] [P1] warning: 1-0:99.97.0: ignoring unknown value ()
[9/21/2020, 16:49:41] [P1] raw data: {"type":"ISK5\\2M550T-1013","checksum":"4E76","version":"5.0","lastupdated":"2020-09-21T17:49:39","id":"E0054007618958020","consumption_low":0,"consumption_normal":1.118,"consumption_back_low":0,"consumption_back_normal":0,"tariff":"normal","power":234,"power_back":0,"failures_short":6,"failures_long":2,"l1_sags":0,"l2_sags":0,"l3_sags":0,"l1_swells":1,"l2_swells":1,"l3_swells":1,"msg_text":"","l1_voltage":228.2,"l2_voltage":227.9,"l3_voltage":228.1,"l1_current":1,"l2_current":0,"l3_current":0,"l1_power":227,"l2_power":0,"l3_power":0,"l1_power_back":0,"l2_power_back":0,"l3_power_back":0,"d1_type":"gas","d1_id":"","d1_lastupdated":"2020-09-21T17:45:06","d1_consumption":2236.009}
[9/21/2020, 16:49:41] [P1] data: {"type":"ISK5\\2M550T-1013","version":"5.0","msg_text":"","electricity":{"id":"E0054007618958020","lastupdated":"2020-09-21T17:49:39","tariff":"normal","consumption":{"low":0,"normal":1.118},"power":234,"failures":{"short":6,"long":2},"l1":{"voltage":228.2,"sags":0,"swells":1,"current":1,"power":227},"l2":{"voltage":227.9,"sags":0,"swells":1,"current":0,"power":0},"l3":{"voltage":228.1,"sags":0,"swells":1,"current":0,"power":0}},"electricityBack":{"id":"E0054007618958020B","lastupdated":"2020-09-21T17:49:39","tariff":"normal","consumption":{"low":0,"normal":0},"power":0,"l1":{"power":0},"l2":{"power":0},"l3":{"power":0}},"gas":{"id":"","lastupdated":"2020-09-21T17:45:06","consumption":2236.009}}
[9/21/2020, 16:49:41] [P1] ISK5\2M550T-1013 v5.0
[9/21/2020, 16:49:41] [P1] Electricity: set Total Consumption from 1.112 kWh to 1.118 kWh
[9/21/2020, 16:49:41] [P1] Electricity: set Total Consumption Normal from 1.112 kWh to 1.118 kWh
[9/21/2020, 16:49:41] [P1] Electricity: set Current Consumption from 216 W to 234 W
[9/21/2020, 16:49:41] [P1] Electricity: set Last Updated from "Mon Sep 21 2020 17:48:04" to "Mon Sep 21 2020 17:49:39"
[9/21/2020, 16:49:41] [P1] Electricity L1: set Current Consumption from 219 W to 227 W
[9/21/2020, 16:49:41] [P1] Electricity L1: set Voltage from 228 V to 228.2 V
[9/21/2020, 16:49:41] [P1] Electricity L2: set Voltage from 227.8 V to 227.9 V
[9/21/2020, 16:49:41] [P1] Electricity History: restored 60 history entries
[9/21/2020, 16:49:41] [P1] warning: RangeError: params.id: invalid id
    at new AccessoryDelegate (/usr/lib/node_modules/homebridge-p1/node_modules/homebridge-lib/lib/AccessoryDelegate.js:50:13)
    at new P1Accessory (/usr/lib/node_modules/homebridge-p1/lib/P1Accessory.js:22:5)
    at new Gas (/usr/lib/node_modules/homebridge-p1/lib/P1Accessory.js:60:5)
    at P1Platform.onData (/usr/lib/node_modules/homebridge-p1/lib/P1Platform.js:184:20)
    at P1Client.<anonymous> (/usr/lib/node_modules/homebridge-p1/lib/P1Platform.js:108:45)
    at P1Client.emit (events.js:315:20)
    at P1Client.parseTelegram (/usr/lib/node_modules/homebridge-p1/lib/P1Client.js:555:12)
    at ReadLineParser.<anonymous> (/usr/lib/node_modules/homebridge-p1/lib/P1Client.js:289:49)
    at ReadLineParser.emit (events.js:315:20)
    at addChunk (_stream_readable.js:295:12)
    at readableAddChunk (_stream_readable.js:267:11)
    at ReadLineParser.Readable.push (_stream_readable.js:212:10)
    at ReadLineParser.Transform.push (_stream_transform.js:152:32)
    at ReadLineParser._transform (/usr/lib/node_modules/homebridge-p1/node_modules/@serialport/parser-delimiter/lib/index.js:35:12)
    at ReadLineParser.Transform._read (_stream_transform.js:191:10)
    at ReadLineParser.Transform._write (_stream_transform.js:179:12)
`

**Comment by ebaauw** [comment]
I think you’re the first to receive a new meter while already running Homebridge P1 on the old meter.  This is obviously not a scenario I have tested.  You might need to remove the old accessories from `cachedAccessories`, using Homebridge Config UI X, or by once starting Homebridge without Homebridge P1, using the `plugins` key in config.json to whitelist your other plugins, or by temporary uninstalling Homebridge P1.

Did they change the gas meter as well, or did they pair your old gas meter to the new electricity meter? Did you already have 3-phase electricity?  Or was that the reason for installing a new meter?

Homebridge P1 also fails to parse the ID of the gas meter.  This causes no new accessory being exposed for the gas meter.  You’re probably still looking at the old accessory for the gas meter.  On first sight the telegram looks fine.  I’m not sure why Homebridge P1 doesn’t parse it.  Maybe it has to do with the old accessories still being cached.  I’ll have to run some tests, but I might not find the time until this weekend.

**Comment by abko** [comment]
They replaced my meter since they had trouble reading it from remote, guess something with the 4G data. 

I have now removed all accessories from cachedAccessories, using Homebridge Config UI X, I also cleared data in Eve, quit the app and restarted. Now all seems to be working again as expected!

Thanks a lot.
