### ISSUE TITLE
Port not found

### ISSUE THREAD

**Issue by Bartelm** [ebaauw/homebridge-p1#27]
Hi,
I bought [this](https://www.robbshop.nl/slimme-meter-kabel?sqr=slimme%20kabel&) exact cable, and a Pi4 (4GB), hooked up to ethernet, installed Homebridge, the Config UI X plugin and this P1 plugin.
I've tested the readouts from the cable, with the RPI using the following command, which works fine.
`screen /dev/ttyUSB0 115200`
But when I fill the config.json file with the standard as below it comes up with log message [homebridge-p1] /dev/ttyUSB0: port not found.
```
"platforms": [
    {
        "name": "Config UI",
        "port": 8080,
        "auth": "form",
        "theme": "dark-mode",
        "restart": "sudo -n systemctl restart homebridge",
        "tempUnits": "c",
        "sudo": true,
        "log": {
            "method": "systemd"
        },
        "accessoryControl": {
            "debug": true
        },
        "platform": "config"
    },
    {
        "name": "homebridge-p1",
        "serialport": "/dev/ttyUSB0",
        "platform": "P1"
    }
]
```

Is there any obvious reason why it wouldn't work?

**Comment by ebaauw** [comment]
Probably because it has a different USB signature than the cables I’ve seen so far.  Current version of homebridge-p1 still checks the signature, even when the serial port device has been specified.

Could you run `homebridge -D` and post the listing of the ports here?

**Comment by Bartelm** [comment]
```
Started Homebridge.
pam_unix(sudo:session): session closed for user root
npm WARN npm npm does not support Node.js v10.15.2
npm WARN npm You should probably upgrade to a newer version of node as we
npm WARN npm can't make any promises that npm will work with this version.
npm WARN npm Supported releases of Node.js are the latest release of 4, 6, 7, 8, 9.
npm WARN npm You can find the latest version at https://nodejs.org/
[05/01/2020, 09:47:08] Loaded config.json with 0 accessories and 2 platforms.
[05/01/2020, 09:47:08] ---
[05/01/2020, 09:47:08] Loaded plugin: homebridge-config-ui-x
[05/01/2020, 09:47:08] Registering platform 'homebridge-config-ui-x.config'
[05/01/2020, 09:47:08] ---
[05/01/2020, 09:47:08] Plugin /usr/local/lib/node_modules/homebridge-p1 requires Node version of ^12.14.0 which does not satisfy the current Node version of v10.15.2. You may need to upgrade your installation of Node.
[05/01/2020, 09:47:10] Loaded plugin: homebridge-p1
[05/01/2020, 09:47:10] Registering platform 'homebridge-p1.P1'
[05/01/2020, 09:47:10] ---
[05/01/2020, 09:47:10] Loading 2 platforms...
[05/01/2020, 09:47:10] [Config UI] Initializing config platform...
[05/01/2020, 09:47:10] [Config UI] Spawning homebridge-config-ui-x with PID 14493
[05/01/2020, 09:47:10] [homebridge-p1] Initializing P1 platform...
[05/01/2020, 09:47:10] [homebridge-p1] homebridge-p1 v0.2.29, node v10.15.2, homebridge v0.4.50
[05/01/2020, 09:47:10] [homebridge-p1] warning: not using recommended node version v12.14.0 LTS
[05/01/2020, 09:47:11] Loading 0 accessories...
[05/01/2020, 09:47:11] [homebridge-p1] /dev/ttyUSB0: port not found
Setup Payload:
X-HM://0023QKS822FAM
Scan this code with your HomeKit app on your iOS device to pair with Homebridge:
```
...
```
Or enter this code with your HomeKit app on your iOS device to pair with Homebridge:
                       
    ┌────────────┐
    │ ...-..-... │
    └────────────┘
                       
[05/01/2020, 09:47:11] Homebridge is running on port 51826.
npm WARN npm npm does not support Node.js v10.15.2
npm WARN npm You should probably upgrade to a newer version of node as we
npm WARN npm can't make any promises that npm will work with this version.
npm WARN npm Supported releases of Node.js are the latest release of 4, 6, 7, 8, 9.
npm WARN npm You can find the latest version at https://nodejs.org/
[05/01/2020, 09:47:17] [Config UI] [HapClient] Discovery :: Started
[05/01/2020, 09:47:17] [Config UI] Homebridge Config UI X v4.6.7 is listening on :: port 8080
[05/01/2020, 09:47:18] [Config UI] [HapClient] Discovery :: Found HAP device with username CB:22:3D:E2:CE:31
[05/01/2020, 09:47:18] [Config UI] [HapClient] Discovery :: Testing CB:22:3D:E2:CE:31 via http://192.168.1.63:51826/accessories
[05/01/2020, 09:47:18] [Config UI] [HapClient] Discovery :: Success CB:22:3D:E2:CE:31 via http://192.168.1.63:51826/accessories
[05/01/2020, 09:47:18] [Config UI] [HapClient] Discovery :: [192.168.1.63:51826 (CB:22:3D:E2:CE:31)] Instance Registered
[05/01/2020, 09:47:20] [Config UI] [HapClient] Discovery :: Found HAP device with username CC:22:3D:E3:CE:30
[05/01/2020, 09:47:20] [Config UI] [HapClient] Discovery :: Testing CC:22:3D:E3:CE:30 via http://192.168.1.63:42113/accessories
[05/01/2020, 09:47:20] [Config UI] [HapClient] Discovery :: Failed CC:22:3D:E3:CE:30 via http://192.168.1.63:42113/accessories
[05/01/2020, 09:47:20] [Config UI] [HapClient] Discovery :: Could not register to device with username CC:22:3D:E3:CE:30
homebridge : TTY=pts/1 ; PWD=/var/lib/homebridge ; USER=root ; COMMAND=/bin/journalctl -o cat -n 500 -f -u homebridge
pam_unix(sudo:session): session opened for user root by (uid=0)
```


`$ lsusb` presents me with this:
```
Bus 003 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
Bus 002 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
Bus 001 Device 003: ID 0403:6001 Future Technology Devices International, Ltd FT232 Serial (UART) IC
Bus 001 Device 002: ID 2109:3431 VIA Labs, Inc. Hub
Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
```

`$ usb-devices` says:
```
T:  Bus=01 Lev=00 Prnt=00 Port=00 Cnt=00 Dev#=  1 Spd=480 MxCh= 1
D:  Ver= 2.00 Cls=09(hub  ) Sub=00 Prot=01 MxPS=64 #Cfgs=  1
P:  Vendor=1d6b ProdID=0002 Rev=04.19
S:  Manufacturer=Linux 4.19.75-v7l+ xhci-hcd
S:  Product=xHCI Host Controller
S:  SerialNumber=0000:01:00.0
C:  #Ifs= 1 Cfg#= 1 Atr=e0 MxPwr=0mA
I:  If#=0x0 Alt= 0 #EPs= 1 Cls=09(hub  ) Sub=00 Prot=00 Driver=hub

T:  Bus=01 Lev=01 Prnt=01 Port=00 Cnt=01 Dev#=  2 Spd=480 MxCh= 4
D:  Ver= 2.10 Cls=09(hub  ) Sub=00 Prot=01 MxPS=64 #Cfgs=  1
P:  Vendor=2109 ProdID=3431 Rev=04.20
S:  Product=USB2.0 Hub
C:  #Ifs= 1 Cfg#= 1 Atr=e0 MxPwr=100mA
I:  If#=0x0 Alt= 0 #EPs= 1 Cls=09(hub  ) Sub=00 Prot=00 Driver=hub

T:  Bus=01 Lev=02 Prnt=02 Port=03 Cnt=01 Dev#=  3 Spd=12  MxCh= 0
D:  Ver= 2.00 Cls=00(>ifc ) Sub=00 Prot=00 MxPS= 8 #Cfgs=  1
P:  Vendor=0403 ProdID=6001 Rev=06.00
S:  Manufacturer=FTDI
S:  Product=FT232R USB UART
S:  SerialNumber=AO3JVMWP
C:  #Ifs= 1 Cfg#= 1 Atr=a0 MxPwr=90mA
I:  If#=0x0 Alt= 0 #EPs= 2 Cls=ff(vend.) Sub=ff Prot=ff Driver=ftdi_sio

T:  Bus=02 Lev=00 Prnt=00 Port=00 Cnt=00 Dev#=  1 Spd=5000 MxCh= 4
D:  Ver= 3.00 Cls=09(hub  ) Sub=00 Prot=03 MxPS= 9 #Cfgs=  1
P:  Vendor=1d6b ProdID=0003 Rev=04.19
S:  Manufacturer=Linux 4.19.75-v7l+ xhci-hcd
S:  Product=xHCI Host Controller
S:  SerialNumber=0000:01:00.0
C:  #Ifs= 1 Cfg#= 1 Atr=e0 MxPwr=0mA
I:  If#=0x0 Alt= 0 #EPs= 1 Cls=09(hub  ) Sub=00 Prot=00 Driver=hub

T:  Bus=03 Lev=00 Prnt=00 Port=00 Cnt=00 Dev#=  1 Spd=480 MxCh= 1
D:  Ver= 2.00 Cls=09(hub  ) Sub=00 Prot=01 MxPS=64 #Cfgs=  1
P:  Vendor=1d6b ProdID=0002 Rev=04.19
S:  Manufacturer=Linux 4.19.75-v7l+ dwc_otg_hcd
S:  Product=DWC OTG Controller
S:  SerialNumber=fe980000.usb
C:  #Ifs= 1 Cfg#= 1 Atr=e0 MxPwr=0mA
I:  If#=0x0 Alt= 0 #EPs= 1 Cls=09(hub  ) Sub=00 Prot=00 Driver=hub
```

**Comment by ebaauw** [comment]
Please run `homebridge -D`: the message I'm looking for is a debug message.

```
Bus 001 Device 003: ID 0403:6001 Future Technology Devices International, Ltd FT232 Serial (UART) IC
```
I think this is the USB P1 converter cable?  Oddly that's exactly the signature homebridge-p1 is looking for.

Are you running homebridge from a docker container or some other virtual environment?  Is the user running homebridge member of the `dialout` group?

**Comment by Bartelm** [comment]
> I think this is the USB P1 converter cable? Oddly that's exactly the signature homebridge-p1 is looking for.

That is the one, it disappears when the usb cable is disconnected. And is the only FTDI device available.

> Are you running homebridge from a docker container or some other virtual environment? Is the user running homebridge member of the dialout group?

No, I've made a new user according to [this installation guide by nfarina](https://github.com/nfarina/homebridge/wiki/Install-Homebridge-on-Raspbian). I've just added the homebridge user to the dialout group for good measure. Strangely enough, the cable already worked when I used the screen package to monitor the serial comms.

The only logs `homebridge -D` gives me I already posted in my second post.

**Comment by ebaauw** [comment]
Odd, I see no debug messages.  Are you capturing stdout as well as stderr?

I don't know what's going on.  Could you try homebridge-p1 v0.2.30 (released earlier today).  That version will simply try to open the given device file, instead of checking that it's returned when searching for serial ports.

If that doesn't work either, try upgrading NodeJS to v12.14.0 (the latest LTS version).  Note that you need to re-build homebridge-p1 and homebridge-config-ui-x after upgrading NodeJS to a different major version.

**Comment by Bartelm** [comment]
A full reset of the Pi (clean image, buster lite, Node v12.14) and a new install of Homebridge and the plugins results in the following log.
```
Started Homebridge.
pam_unix(sudo:session): session closed for user root
[1/5/2020, 7:06:42 PM] Loaded config.json with 0 accessories and 2 platforms.
[1/5/2020, 7:06:42 PM] ---
[1/5/2020, 7:06:42 PM] Loaded plugin: homebridge-config-ui-x
[1/5/2020, 7:06:42 PM] Registering platform 'homebridge-config-ui-x.config'
[1/5/2020, 7:06:42 PM] ---
[1/5/2020, 7:06:44 PM] Loaded plugin: homebridge-p1
[1/5/2020, 7:06:44 PM] Registering platform 'homebridge-p1.P1'
[1/5/2020, 7:06:44 PM] ---
[1/5/2020, 7:06:44 PM] Loading 2 platforms...
[1/5/2020, 7:06:44 PM] [Config] Initializing config platform...
[1/5/2020, 7:06:44 PM] [Config] Spawning homebridge-config-ui-x with PID 3799
[1/5/2020, 7:06:44 PM] [SlimmeMeter] Initializing P1 platform...
[1/5/2020, 7:06:44 PM] [SlimmeMeter] homebridge-p1 v0.2.30, node v12.14.0, homebridge v0.4.50
[1/5/2020, 7:06:44 PM] Loading 0 accessories...
[1/5/2020, 7:06:44 PM] [SlimmeMeter] error: SyntaxError: port: invalid key
    at newSyntaxError (/usr/lib/node_modules/homebridge-p1/node_modules/homebridge-lib/lib/OptionParser.js:37:52)
    at OptionParser.parse (/usr/lib/node_modules/homebridge-p1/node_modules/homebridge-lib/lib/OptionParser.js:791:17)
    at new P1Client (/usr/lib/node_modules/homebridge-p1/lib/P1Client.js:284:18)
    at /usr/lib/node_modules/homebridge-p1/lib/P1Platform.js:125:15
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
Setup Payload:
X-HM://0023QKS823J6B
Scan this code with your HomeKit app on your iOS device to pair with Homebridge:
```

**Comment by ebaauw** [comment]
That’s my bad.  Will issue a fix shortly.  What happens when you don’t specify `serialPort` in config.json?

**Comment by ebaauw** [comment]
v0.2.32 is out, with fix.  Had an argument with `npm` (which I lost), so skipped a version.

**Comment by Bartelm** [comment]
With this fix the measurements flow through the logs. Thanks!

Maybe off-topic for this issue, but no accessories were created. Not before nor after the fix. Do I do this by hand? I read in the readme it should create itself.

> What happens when you don’t specify `serialPort` in confit.json?

I’ll try that tonight after work.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by ebaauw** [comment]
You might need to increase `timeout`.  Isn’t there any message in the log that the first telegram arrived too late?

**Comment by Bartelm** [comment]
Set a timeout. Works like a charm! Thanks @ebaauw 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
